overblog_graphql_subscription_multiple_endpoint:
    path: /{schemaName}
    methods: POST
    defaults:
        _controller: Overblog\GraphQLSubscription\Bridge\Symfony\Action\SubscriptionAction
        _format: "json"
    requirements:
        schemaName: '[^/]+'
