services:
    Overblog\GraphQLSubscription\Bridge\Symfony\EventListener\SpoolNotificationsHandler:
        arguments:
            - '@Overblog\GraphQLSubscription\SubscriptionManager'
        tags:
            - {name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate}
